### ISSUE TITLE
Treat documentation as the first citizen at the Jakarta NoSQL project.

### ISSUE THREAD

**Issue by otaviojava** [eclipse-ee4j/nosql#121]
We go to another approval at the Jakarta EE committee board, which is good news.

As the next step, I would like to create a force task to review and enhances our project documentation.

## Tasks

- [x] [Readme](https://github.com/eclipse-ee4j/nosql/issues/117)
- [x] [Create changelog](https://github.com/eclipse-ee4j/nosql/issues/118)
- [x] [Review JavaDoc](https://github.com/eclipse-ee4j/nosql/issues/119)
- [x] [Refactoring Spec](https://github.com/eclipse-ee4j/nosql/issues/120)

**Comment by mpredli01** [comment]
Hey Otavio:

That is indeed great news!  I am more-than-happy to help with the documentation.

Mike.

**Comment by DanSilva41** [comment]
Great initiative!
I am very excited and willing to collaborate!

The idea is to assign the issue and get to work?

Thank you, @otaviojava!
_Danilo Silva_

**Comment by andradesampaio** [comment]
Hi @otaviojava,

Make me available to collaborate!

Andrade Sampaio

**Comment by otaviojava** [comment]
Hey @DanSilva41, yes, it is simple like that.
Take an issue and start a discussion on it.

**Comment by otaviojava** [comment]
@andradesampaio, how about you start with this one?
https://github.com/eclipse-ee4j/nosql/issues/120
It is to remove the concept of it.
It might be an easier one.

https://github.com/eclipse-ee4j/nosql/tree/main/spec/src/main/asciidoc

**Comment by DanSilva41** [comment]
Excellent, @otaviojava !!
Thanks, let's go 🚀

**Comment by otaviojava** [comment]
Please, comment on the issue that you wanna work on to avoid duplicated efforts.

**Comment by DanSilva41** [comment]
Ah yes! I believe that a good start would be to start the discussions of #118!

Could it be? @otaviojava

**Comment by otaviojava** [comment]
Yes, please, create a discussion there :)
Put reference, create a template, and then a PR.

**Comment by otaviojava** [comment]
@DanSilva41 are you going to do the changelog on the mapping?
https://github.com/eclipse/jnosql-mapping-extension/
Btw, thank you for all the work!

**Comment by otaviojava** [comment]
Hello everyone.

Thank you for all the help on this issue.
It was excellent teamwork.

Thank you @mpredli01 @DanSilva41 @andradesampaio 

For sure, more enhancement on the documentation is welcome.

But, I'll close this issue.
